#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# scripts/emit-consumer-pin.sh [release-tag]
#
# Emits dist/ffmpeg-pin.lock -- THE SINGLE SOURCE OF TRUTH that both consumers
# vendor verbatim, so nelux and TheAnimeScripter cannot drift apart.
#
# WHY THIS FILE EXISTS
#   There is no --build-suffix. nelux's bundled libav* and TAS's
#   ffmpeg_shared/libav* have identical file names, so on Windows whichever
#   loads first serves both processes-worth of calls. That is safe if and only
#   if they are the SAME build. Today nothing enforces that: nelux pins FFmpeg
#   in D:\Nelux\tools\ffmpeg.lock and TAS duplicates those values by hand in
#   src/infra/getFFMPEG.py -- that file's own header says so, at lines 16-20:
#     "TheAnimeScripter's src/infra/getFFMPEG.py is a separate repo and
#      duplicates WIN64_BTBN_* for the same reason. Change a WIN64_BTBN_*
#      value here and you MUST mirror it in both."
#   A hand-mirrored pin across two repos is a drift generator.
#
#   ffmpeg-pin.lock replaces that. It is published as a release asset in the
#   SAME KEY=value format nelux/tools/ffmpeg.lock already parses (that format
#   was chosen to be readable from bash, PowerShell, Python and GH Actions
#   alike), so each consumer's existing download script needs only to point at
#   this file instead of hand-maintaining URLs and hashes.
#
#   Pair it with manifest.json (scripts/make-manifest.sh) for the runtime half
#   of the contract: the pin file says which build to fetch, the manifest says
#   how to assert at startup that you actually loaded it.
#
# Run AFTER package.sh has produced every platform's archive, or pass the
# release tag and let CI fill in the URLs.
# ---------------------------------------------------------------------------
set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
load_lock

TAG="${1:-v$FFMPEG_VERSION}"
REPO_SLUG="${GITHUB_REPOSITORY:-NevermindNilas/TAS-FFMPEG}"
BASE="https://github.com/$REPO_SLUG/releases/download/$TAG"
OUT="$DIST_DIR/ffmpeg-pin.lock"

mkdir -p "$DIST_DIR"

emit_platform() {  # <KEY_PREFIX> <os> <arch> <ext>
  local key="$1" os="$2" arch="$3" ext="$4" name file
  name="$(artifact_name "$os" "$arch")"
  file="$DIST_DIR/$name.$ext"
  if [ ! -f "$file" ]; then
    printf '# %s: NOT BUILT in this run -- keys omitted deliberately rather than guessed\n\n' "$key"
    return
  fi
  cat <<EOF
${key}_VERSION=$FFMPEG_VERSION
${key}_FILE=$name.$ext
${key}_ROOT=$name
${key}_URL=$BASE/$name.$ext
${key}_SHA256=$(sha256_of "$file")

EOF
}

cat > "$OUT" <<EOF
# ffmpeg-pin.lock -- SINGLE SOURCE OF TRUTH for the FFmpeg binaries that
# nelux AND TheAnimeScripter both consume. Generated by
# tas-ffmpeg/scripts/emit-consumer-pin.sh; do not hand-edit.
#
# Format: KEY=value, one per line, no quotes, no spaces around '='.
# '#' starts a comment. Deliberately parseable by bash
# (\`sed -n 's/^KEY=//p'\`), PowerShell (a \`-match '^([A-Z0-9_]+)=(.*)\$'\`
# loop), Python and GitHub Actions alike -- the same contract
# D:\\Nelux\\tools\\ffmpeg.lock already uses.
#
# HOW TO USE THIS
#   Each consumer should FETCH this file for the release it targets and read
#   the values, instead of hand-mirroring URLs and hashes into its own repo.
#   That hand-mirroring is what this file exists to eliminate: see the header
#   of D:\\Nelux\\tools\\ffmpeg.lock lines 16-20, which currently instructs a
#   human to keep three copies in sync by hand.
#
#   Every consumer MUST verify the SHA256 before using a download and MUST
#   fail loudly on mismatch.
#
# WHY BOTH CONSUMERS MUST USE THE SAME RELEASE
#   These builds carry NO --build-suffix, so nelux's bundled libraries and
#   TAS's ffmpeg_shared libraries have identical file names. On Windows the
#   first one loaded into a process serves both. Identical builds: safe.
#   Mismatched builds: undefined behaviour, and nothing at the OS level
#   prevents it. Assert AV_VERSION_INFO below (or manifest.json inside the
#   archive) at startup and fail loudly.
#
# ===========================================================================
# Identity -- assert these at runtime
# ===========================================================================
FFMPEG_VERSION=$FFMPEG_VERSION
FFMPEG_TAG=$FFMPEG_TAG
FFMPEG_COMMIT=$FFMPEG_COMMIT
FFMPEG_TARBALL_SHA256=$FFMPEG_SHA256
# av_version_info() returns exactly this string. Built with
# --extra-version=tas, so no distro, gyan or BtbN FFmpeg can ever match it --
# the assertion catches "wrong build" as well as "wrong version".
AV_VERSION_INFO=$FFMPEG_VERSION-tas

# Shared-library ABI. Identical to the seven majors D:\\Nelux\\tools\\ffmpeg.lock
# lines 30-31 already targets.
SONAME_AVCODEC=$SONAME_AVCODEC
SONAME_AVDEVICE=$SONAME_AVDEVICE
SONAME_AVFILTER=$SONAME_AVFILTER
SONAME_AVFORMAT=$SONAME_AVFORMAT
SONAME_AVUTIL=$SONAME_AVUTIL
SONAME_SWRESAMPLE=$SONAME_SWRESAMPLE
SONAME_SWSCALE=$SONAME_SWSCALE

# Licensing of the shipped binaries.
LICENSE_SPDX=GPL-2.0-or-later
CORRESPONDING_SOURCE_URL=$BASE/tas-ffmpeg-$FFMPEG_VERSION-corresponding-source.tar.xz

# Files to preserve out of every archive (same key TAS/nelux already honour).
LICENSE_GLOBS=licenses;LICENSE*;COPYING*;GPL*

# ===========================================================================
# Per-platform archives
# ===========================================================================
EOF

{
  emit_platform WIN64       windows x86_64 zip
  emit_platform LINUX64     linux   x86_64 tar.xz
  # Key name deliberately mirrors nelux's existing LINUXARM64_BTBN_* block
  # (D:\Nelux\tools\ffmpeg.lock:113-119) so the consumer-side change is a
  # prefix swap, not a rewrite.
  emit_platform LINUXARM64  linux   arm64  tar.xz
  emit_platform MACOS_ARM64 macos   arm64  tar.xz
  emit_platform MACOS_X64   macos   x86_64 tar.xz
} >> "$OUT"

cat >> "$OUT" <<'EOF'
# All five targets are built by this repo: win64, linux64, linuxarm64,
# macos-arm64, macos-x86_64. A "NOT BUILT in this run" comment above means
# that platform's job did not produce an archive in THIS invocation (e.g. a
# single-platform local run) -- keys are omitted rather than guessed.
#
# *** MACOS_X64 HAS A KNOWN END DATE: AUGUST 2027. ***
# GitHub-hosted Intel macOS runners (the `macos-*-intel` labels this repo
# builds on) are the last x86_64 images on GitHub Actions, and GitHub has
# stated that x86_64 will not be supported on Actions after August 2027
# (actions/runner-images#13045). When that happens the MACOS_X64_* keys will
# stop appearing in this file.
#
# CONSUMERS MUST TREAT A MISSING PLATFORM BLOCK AS A HARD ERROR, NOT AS
# "fall back to the previous release". Silently reusing an older archive is
# exactly the drift this file exists to eliminate, and on macOS it would also
# mean loading a DIFFERENT build of identically-named libraries into the same
# process as a current one -- see the co-loading warning above. If a platform
# you need is absent, fail loudly and open an issue on this repo.
#
# PER-PLATFORM FEATURE DIFFERENCES (see README.md#encoders-per-platform):
#   NVENC/NVDEC/CUVID   everywhere except macOS
#   QSV (libvpl)        Windows + Linux x86_64 only
#   AMF                 Windows + Linux x86_64 only
#   MediaFoundation     Windows only  (h264_mf, hevc_mf)
#   VideoToolbox        macOS only    (h264/hevc/prores_videotoolbox)
#   libx264/libx265/libsvtav1/libaom/libvpx/libopenh264/libopus/libzimg/
#   libvmaf and a TLS backend for https:// exist on ALL five.
EOF

log "wrote $OUT"
cat "$OUT" >&2
